apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-nginx
  labels:
    env: demo
spec:
  template:
    metadata:
      name: pod-nginx
      labels:
        env: demo
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      env: demo
